name: "Helm Unit Tests"
description: "Run Helm chart unit tests with quintush/helm-unittest"

inputs:
  flags:
    description: "Flags to pass to helm unittest"
    required: false
    default: "-3 --color"

  charts:
    description: "Charts to run tests for, separated by spaces"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      shell: bash

    - run: helm plugin install https://github.com/quintush/helm-unittest
      shell: bash

    - run: |
        tr ' ' '\n' <<< "${{ inputs.charts }}" | grep -v '^$' > charts-to-test
        find . -type f -name 'Chart.yaml' -exec dirname {} \; > all-charts
        [ -z "${{ inputs.charts }}" ] && mv all-charts charts-to-test || true
      shell: bash

    - run: |
        for chart in $(cat charts-to-test); do
          helm dependency update "$chart"
        done
      shell: bash

    - run: helm unittest ${{ inputs.flags }} $(cat charts-to-test)
      shell: bash
