name: "Helm Unit Tests"
description: "Run Helm chart unit tests with quintush/helm-unittest"

inputs:
  flags:
    description: "Flags to pass to helm unittest"
    required: false
    default: "-3 --color"

  charts:
    description: "List of charts to run tests for"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      shell: bash

    - run: helm plugin install https://github.com/quintush/helm-unittest
      shell: bash

    - shell: bash
      run: |
        charts="${{ inputs.charts }}"

        if [ -z "$charts" ]; then
          charts="$(find . -type f -name 'Chart.yaml' -exec dirname {} \;)"
        fi

        for chart in $charts; do
          helm dependency update "$chart"
        done

        helm unittest ${{ inputs.flags }} $charts
